### PR TITLE
Feature/1 setup GitHub actions pipeline to build and publish package to npm

### LINKED ISSUE #1: Setup GitHub Actions pipeline to build and publish package to NPM
In the further process of development we need to add a GitHub Actions pipeline that:
- builds our Web Components
- tests our Web Components (unit & e2e tests)
- publishes the updated Web Components to NPM

### PR DESCRIPTION
**Pull request by BernhardHuberPlanBGmbH**
Added pipeline that runs on main push to build components and publish them on NPM.

## Changes

- Added new build & publish pipeline (publishes to NPM)

## Checklist

- [ ] Changed e2e tests
- [ ] Changed unit tests
- [ ] Successfully executed unit tests locally
- [ ] Successfully executed e2e tests locally
- [ ] Ran linter
- [ ] Bumped version

Closes #1 

@PlanBGmbH/flinkey-web-components

### CODE REVIEW

**Comment by aaronczichon** [comment]
This currently only includes the publishing. That's the thing I mentioned yesterday:
You need to ensure, that you update and commit the `package.json` first in the workflow before submitting the package. Otherwise you get a conflict on NPM `a package with this version is already published`.

**Comment by aaronczichon** [comment]
Also: your workflow says `master` as trigger. Should be changed to `main` ;)

**Comment by BernhardHuberPlanBGmbH** [comment]
> This currently only includes the publishing. That's the thing I mentioned yesterday:
> You need to ensure, that you update and commit the `package.json` first in the workflow before submitting the package. Otherwise you get a conflict on NPM `a package with this version is already published`.

Yes, I'll check this.

**Review by aaronczichon — APPROVED** [review]
Perfecto

**Pull request merged**
